### ISSUE TITLE
Playwright tests fail if someone edits metadata

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/opencast-editor#581]
After editing the metadata on editor.opencast.org, the Plawright tests start failing since they have the originally igested values hard-coded. We shouldn't rely on any values which can easily change due to unrelated external input:

```
      -   unexpected value "00:00:10"
      -   selector resolved to <input value="00:00:10" id="catalog0.duration" name="ca…/>
      -   unexpected value "00:00:10"
      -   selector resolved to <input value="00:00:10" id="catalog0.duration" name="ca…/>
      -   unexpected value "00:00:10"
      -   selector resolved to <input value="00:00:10" id="catalog0.duration" name="ca…/>
      -   unexpected value "00:00:10"
      -   selector resolved to <input value="00:00:10" id="catalog0.duration" name="ca…/>
      -   unexpected value "00:00:10"
      -   selector resolved to <input value="00:00:10" id="catalog0.duration" name="ca…/>
      -   unexpected value "00:00:10"
      -   selector resolved to <input value="00:00:10" id="catalog0.duration" name="ca…/>
      -   unexpected value "00:00:10"


      13 |         for(let i = 0; i < input.length; i++) {
      14 |             const locator = page.locator('input[name="catalog0.' + input[i] + '"]');
    > 15 |             await expect(locator).toHaveValue(iValue[i]);
         |                                   ^
      16 |             await page.click('input[name="catalog0.' + input[i] + '"]');
      17 |             await page.fill('input[name="catalog0.' + input[i] + '"]', iFill[i]);
      18 |         }

        at /home/runner/work/opencast-editor/opencast-editor/tests/metadata.test.ts:15:35
        at /home/runner/work/opencast-editor/opencast-editor/node_modules/@playwright/test/lib/workerRunner.js:529:7
        at WorkerRunner._runFn (/home/runner/work/opencast-editor/opencast-editor/node_modules/@playwright/test/lib/workerRunner.js:575:7)
        at WorkerRunner._runTestWithBeforeHooks (/home/runner/work/opencast-editor/opencast-editor/node_modules/@playwright/test/lib/workerRunner.js:523:20)
Error:   2) [firefox] › tests/metadata.test.ts:11:5 › Test Metadata-Page › Check Inputfields ==============
```

**Comment by Arnei** [comment]
Related: #565

**Comment by lkiesow** [comment]
Yep, sorry, indeed, this duplicates #565
