### ISSUE TITLE
Add volume control

### ISSUE THREAD

**Issue by Arnei** [elan-ev/opencast-editor#80]
It may be nice to be able to adjust the volume of the video, instead of having to rely on global or browser volume controls.

**Comment by A98Rahman** [comment]
Can I work on this if it has not been done already? Looking to get into open source development. I am recent comp-sci graduate.

**Comment by lkiesow** [comment]
Hi @A98Rahman, sure, please go ahead. I've assigned this to you.
Thanks for helping out.

**Comment by A98Rahman** [comment]
Hi @lkiesow,

Thank you for assigning this to me. 

I am facing an issue while getting the project to run. When I execute 'npm start' this is the error I get, 22 error opencast-editor@0.1.0 start: `REACT_APP_GIT_SHA=`git rev-parse HEAD` REACT_APP_BUILD_DATE="`date`" react-app-rewired start`. 

I have tried cleaning caches, running 'npm install' and other possible solutions. I started out on windows 11 but then switched tto Ubuntu 20.04.5 LTS but the problem persists.

The npm debug log reads below.
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle opencast-editor@0.1.0~prestart: opencast-editor@0.1.0
6 info lifecycle opencast-editor@0.1.0~start: opencast-editor@0.1.0
7 verbose lifecycle opencast-editor@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle opencast-editor@0.1.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/arable/project/opencast-editor/node_modules/.bin:/home/arable/Downloads/wkspc/simu5G/bin:/home/arable/Downloads/wkspc/omnetpp-6.0pre11-src-linux/omnetpp-6.0pre11/bin:/home/arable/Downloads/wkspc/sumo-all-1.8.0/sumo-1.8.0/bin:/home/arable/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle opencast-editor@0.1.0~start: CWD: /home/arable/project/opencast-editor
10 silly lifecycle opencast-editor@0.1.0~start: Args: [ '-c',
10 silly lifecycle   'REACT_APP_GIT_SHA=`git rev-parse HEAD` REACT_APP_BUILD_DATE="`date`" react-app-rewired start' ]
11 silly lifecycle opencast-editor@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle opencast-editor@0.1.0~start: Failed to exec start script
13 verbose stack Error: opencast-editor@0.1.0 start: `REACT_APP_GIT_SHA=`git rev-parse HEAD` REACT_APP_BUILD_DATE="`date`" react-app-rewired start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid opencast-editor@0.1.0
15 verbose cwd /home/arable/project/opencast-editor
16 verbose Linux 5.13.0-30-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error opencast-editor@0.1.0 start: `REACT_APP_GIT_SHA=`git rev-parse HEAD` REACT_APP_BUILD_DATE="`date`" react-app-rewired start`
22 error Exit status 1
23 error Failed at the opencast-editor@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by lkiesow** [comment]
`npm start` should actually be `npm run start`. Feel free to create a pull request, updating the readme ;-D
Also, as with all `npm` based projects, remember to install dependencies via `npm ci` or `npm install` before trying to start the app

**Comment by A98Rahman** [comment]
I have tried to install the dependencies multiple times over. This is the error that I am persistently getting. 

> opencast-editor@0.1.0 start /home/arable/project/opencast-editor
> REACT_APP_GIT_SHA=`git rev-parse HEAD` REACT_APP_BUILD_DATE="`date`" react-app-rewired start

/home/arable/project/opencast-editor/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/arable/project/opencast-editor/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencast-editor@0.1.0 start: `REACT_APP_GIT_SHA=`git rev-parse HEAD` REACT_APP_BUILD_DATE="`date`" react-app-rewired start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencast-editor@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arable/.npm/_logs/2022-10-25T21_00_11_015Z-debug.log

Unsure if the dependency /eslint-webpack-plugin/ is causing unexpected behaviour. Is it something that you have come across previously?

**Comment by Arnei** [comment]
I can't say that I have come across this previously, nor am I sure how to resolve this. `npm cache clean` and `npm install` usually solve stuff like this for me :').
